image: 
  - Visual Studio 2017
environment:
  matrix:
  - RUST_TOOL_CHAIN: stable
  #- RUST_TOOL_CHAIN: nightly
install:
  - ps: Start-FileDownload "https://win.rustup.rs/x86_64" -FileName "rustup-init.exe"
  - rustup-init.exe -y --default-toolchain %RUST_TOOL_CHAIN%
  - SET PATH=%USERPROFILE%\.cargo\bin;C:\MinGW\bin;%PATH%
  - rustc -V
  - cargo -V
build_script:
  - cargo build --release
  #- dotnet build -c Release dotnet/RuAnnoy.sln
test_script:
  - cargo test --release
  #- dotnet test -c Release dotnet/RuAnnoy.sln
branches:
  only:
    - master
artifacts:
  - path: '**\*.nupkg'
nuget:
  disable_publish_on_pr: true
#deploy:
#  provider: NuGet
#  api_key:
#    secure: nNWiXk+ZiOOh5sHV/C9Z9pqZ8GFpaQFqAR/P0/t09h81Ppx3xed6VsWd4w7FMn2R
