[package]
name = "ru_fastemd"
version = "0.1.0"
authors = ["hanabi1224"]
license = "MIT"
repository = "https://github.com/hanabi1224/RuFastEMD"
description = """
A rust implementation of fast emd algrithm
"""

[dependencies]
libc = "0.2"


[lib]
crate-type = ["lib", "cdylib"]
